trigger:
- master

pool:
  vmImage: Ubuntu-16.04

variables:
  imageName: azure-pipelines-canary-k8s
  dockerRegistryServiceConnection: dockerhub-pipelines-canary-k8s 
  imageRepository: galache
  containerRegistry: index.docker.io
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: Ubuntu-16.04
    steps:
    - task: Docker@2
      name: task_dockerhub_login
      inputs:
          containerRegistry: '$(dockerRegistryServiceConnection)'
          command: 'login'
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)/$(imageName)
        command: buildAndPush
        Dockerfile: app/Dockerfile
        tags: |
          tag